# This is a basic workflow to help you get started with Actions

name: Test SDK

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  arch: x64

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check SDK Version
        shell: powershell
        run: |
          $(Get-Item "hklm:\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows").GetValue("CurrentVersion")

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Download artifacts
  #     uses: actions/download-artifact@v2

  #   - name: Publish release
  #     uses: marvinpinto/action-automatic-releases@v1.2.1
  #     with:
  #       repo_token: "${{secrets.GITHUB_TOKEN}}"
  #       automatic_release_tag: latest
  #       prerelease: true
  #       files: build/TaigaSetup.exe
